### ISSUE TITLE
[Bug] Scenario.Run should return success iff the run succeeded for appropriate definition of success

### ISSUE THREAD

**Issue by dandavison** [temporalio/omes#63]
We've noticed that `Scenario.Run` returns a non-error result in circumstances when it should clearly report an error: for example no worker was running and none of the workflows ever completed.

Define success appropriately (perhaps with CLI arguments influencing the definition) and ensure that   the return value honors the definition.

**Comment by bergundy** [comment]
This only happens when you run a scenario with a duration parameter, not with an iteration count.
`GenericExecutor` doesn't not count run errors if they're emitted after the scenario deadline is exceeded.
Some ideas:
1. Put an optional deadline the context for each iteration - this works if the iteration deadline is shorter than the scenario deadline
2. Add a scenario option to require at least X successes
